"""SQL generated by `create_pagination`.

The module is loaded from its file: importing the `ayon_server.graphql`
package builds the whole schema, which requires a database connection.

The tests at the end run the generated SQL in Postgres and are skipped
when the database (AYON_POSTGRES_URL) is not available.
"""

import asyncio
import importlib.util
import os
import sys
from typing import Any

import pytest

BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, BACKEND_DIR)

from ayon_server.exceptions import BadRequestException  # noqa: E402

_spec = importlib.util.spec_from_file_location(
    "pagination",
    os.path.join(BACKEND_DIR, "ayon_server", "graphql", "resolvers", "pagination.py"),
)
assert _spec and _spec.loader
pagination = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(pagination)

create_pagination = pagination.create_pagination
decode_cursor = pagination.decode_cursor
encode_cursor = pagination.encode_cursor


ATTRIB = "(folders.attrib->>'fps')"


def test_cursor_roundtrip():
    cursor = [None, 5, "a'b", "2024-01-01T00:00:00+00:00"]
    assert decode_cursor(encode_cursor(cursor)) == cursor
    assert decode_cursor(None) == []


def test_invalid_cursor():
    with pytest.raises(BadRequestException):
        decode_cursor("not a cursor")
    with pytest.raises(BadRequestException):
        decode_cursor(encode_cursor({"a": 1}))  # type: ignore[arg-type]


def test_first_page():
    ordering, conditions, cursor = create_pagination(
        ["folders.name", "folders.id"], first=10
    )
    assert conditions == ""
    assert ordering == (
        "ORDER BY folders.name ASC NULLS LAST, folders.id ASC NULLS LAST LIMIT 20"
    )
    assert cursor == "folders.name AS cursor_0, folders.id AS cursor_1"


def test_last_page_is_descending():
    ordering, conditions, _ = create_pagination([ATTRIB, "hierarchy.path"], last=5)
    assert conditions == ""
    assert ordering == (
        f"ORDER BY {ATTRIB} DESC NULLS FIRST, hierarchy.path DESC NULLS FIRST LIMIT 10"
    )


def test_non_nullable_keys_use_row_comparison():
    after = encode_cursor(["foo", "0123"])
    _, conditions, _ = create_pagination(
        ["folders.name", "folders.id"], first=10, after=after
    )
    assert conditions == "(folders.name, folders.id) > ('foo'::text, '0123'::text)"

    before = encode_cursor([42])
    _, conditions, _ = create_pagination(
        ["folders.creation_order"], last=10, before=before
    )
    assert conditions == "folders.creation_order < 42"


def test_after_value():
    after = encode_cursor(["25", "/a"])
    _, conditions, _ = create_pagination(
        [ATTRIB, "hierarchy.path"], first=10, after=after
    )
    key = f"({ATTRIB})::text"
    assert conditions == (
        f"((({key} > '25'::text OR {key} IS NULL))"
        f" OR ({key} = '25'::text AND hierarchy.path > '/a'::text))"
    )


def test_after_null():
    """Only the rows with NULL are after a NULL value"""
    after = encode_cursor([None, "/assets"])
    _, conditions, _ = create_pagination(
        [ATTRIB, "hierarchy.path"], first=10, after=after
    )
    assert conditions == (f"(({ATTRIB}) IS NULL AND hierarchy.path > '/assets'::text)")


def test_before_value():
    before = encode_cursor([5, 3])
    _, conditions, _ = create_pagination(["label", "position"], last=10, before=before)
    assert conditions == (
        "(((label)::numeric < 5::numeric)"
        " OR ((label)::numeric = 5::numeric AND (position)::numeric < 3::numeric))"
    )


def test_before_null():
    """All values are before NULL"""
    before = encode_cursor([None, 5])
    _, conditions, _ = create_pagination(["label", "position"], last=10, before=before)
    assert conditions == (
        "(((label) IS NOT NULL)"
        " OR ((label) IS NULL AND (position)::numeric < 5::numeric))"
    )


def test_after_null_in_last_key():
    after = encode_cursor([None])
    _, conditions, _ = create_pagination(["label"], first=10, after=after)
    assert conditions == "FALSE"

    before = encode_cursor([None])
    _, conditions, _ = create_pagination(["label"], last=10, before=before)
    assert conditions == "((label) IS NOT NULL)"


def test_quotes_are_escaped():
    after = encode_cursor(["it's", "o'k"])
    _, conditions, _ = create_pagination(
        ["label", "folders.name"], first=10, after=after
    )
    assert "'it''s'::text" in conditions
    assert "'o''k'::text" in conditions


def test_invalid_timestamp():
    after = encode_cursor(["yesterday"])
    with pytest.raises(BadRequestException):
        create_pagination(["events.created_at"], first=10, after=after)


#
# Paging through rows with NULL sort values in Postgres
# returns every row exactly once
#


@pytest.fixture(scope="module")
def database():
    """Return a coroutine function opening a database connection.

    Skips the tests when the database is not available.
    """
    import asyncpg

    from ayon_server.config import ayonconfig

    async def connect() -> Any:
        return await asyncpg.connect(ayonconfig.postgres_url, timeout=5)

    async def probe() -> None:
        conn = await connect()
        await conn.close()

    try:
        asyncio.run(probe())
    except Exception as e:
        pytest.skip(f"Database is not available: {e}")
    return connect


# id, label, num, data
ROWS = [
    ("01", "b", 2, '{"fps": "25"}'),
    ("02", None, 1, '{"fps": "25"}'),
    ("03", "a", None, "{}"),
    ("04", None, None, '{"fps": null}'),
    ("05", "b", 1, '{"fps": "24"}'),
    ("06", "it's", None, '{"fps": "30"}'),
    ("07", None, 2, "{}"),
    ("08", "a", 2, '{"fps": "25"}'),
    ("09", "b", None, '{"fps": "24"}'),
    ("10", None, 1, "{}"),
    ("11", "c", 3, '{"fps": "30"}'),
]

SORTINGS = [
    ["t.label", "t.id"],
    ["t.num", "t.id"],
    ["(t.data->>'fps')", "t.id"],
    ["t.label", "t.num", "t.id"],
    ["t.num", "t.label", "t.id"],
]


def _query(order_by: list[str], **kwargs: Any) -> str:
    ordering, conditions, cursor = create_pagination(order_by, **kwargs)
    values = ", ".join(
        "('{}', {}, {}, '{}'::jsonb)".format(
            id,
            "NULL" if label is None else "'{}'".format(label.replace("'", "''")),
            "NULL" if num is None else num,
            data,
        )
        for id, label, num, data in ROWS
    )
    return f"""
        WITH t(id, label, num, data) AS (VALUES {values})
        SELECT t.id, {cursor} FROM t
        {"WHERE " + conditions if conditions else ""}
        {ordering}
    """


async def _walk(
    conn: Any, order_by: list[str], page_size: int, backwards: bool
) -> list[str]:
    result: list[str] = []
    cursor: str | None = None
    for _ in range(len(ROWS) + 1):
        if backwards:
            query = _query(order_by, last=page_size, before=cursor)
        else:
            query = _query(order_by, first=page_size, after=cursor)
        page = (await conn.fetch(query))[:page_size]
        if not page:
            return result
        result.extend(row["id"] for row in page)
        last_row = page[-1]
        cursor = encode_cursor([last_row[f"cursor_{i}"] for i in range(len(order_by))])
    raise AssertionError("Paging did not finish")


async def _all(conn: Any, order_by: list[str], backwards: bool) -> list[str]:
    kwargs = {"last": len(ROWS)} if backwards else {"first": len(ROWS)}
    return [row["id"] for row in await conn.fetch(_query(order_by, **kwargs))]


@pytest.mark.parametrize("order_by", SORTINGS, ids=lambda s: ",".join(s))
@pytest.mark.parametrize("backwards", [False, True], ids=["forward", "backward"])
@pytest.mark.parametrize("page_size", [1, 2, 3])
def test_paging_returns_every_row_once(database, order_by, backwards, page_size):
    async def check():
        conn = await database()
        try:
            expected = await _all(conn, order_by, backwards)
            assert sorted(expected) == sorted(row[0] for row in ROWS)
            assert await _walk(conn, order_by, page_size, backwards) == expected
        finally:
            await conn.close()

    asyncio.run(check())
