"""SQL generated by `build_filter` for the text matching operators."""

import os
import sys

import pytest

BACKEND_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, BACKEND_DIR)

from ayon_server.sqlfilter import (  # noqa: E402
    QueryCondition,
    QueryFilter,
    build_condition,
    build_filter,
)


def test_like_on_attribute():
    condition = QueryCondition(key="attrib.note", operator="like", value="%foo%")
    assert build_condition(condition) == "(attrib->>'note') ILIKE '%foo%'"


def test_notlike_on_attribute_keeps_missing_values():
    condition = QueryCondition(key="attrib.note", operator="notlike", value="%foo%")
    assert (
        build_condition(condition)
        == "NOT coalesce((attrib->>'note') ILIKE '%foo%', FALSE)"
    )


def test_notlike_on_column():
    condition = QueryCondition(key="name", operator="notlike", value="%foo%")
    assert (
        build_condition(condition, table_prefix="tasks")
        == "NOT coalesce((tasks.name) ILIKE '%foo%', FALSE)"
    )


@pytest.mark.parametrize("operator", ["notlike", "not_like", "NOT-LIKE", "NotLike"])
def test_notlike_operator_spelling(operator: str):
    condition = QueryCondition(key="attrib.note", operator=operator, value="%a%")
    assert condition.operator == "notlike"


def test_notlike_escapes_quotes():
    condition = QueryCondition(key="attrib.note", operator="notlike", value="%it's%")
    assert "ILIKE '%it''s%'" in build_condition(condition)


def test_notlike_requires_string_value():
    condition = QueryCondition(key="attrib.note", operator="notlike", value=1)
    with pytest.raises(ValueError):
        build_condition(condition)


def test_notlike_conditions_in_filter():
    f = QueryFilter(
        operator="and",
        conditions=[
            QueryCondition(key="attrib.note", operator="notlike", value="%a%"),
            QueryCondition(key="attrib.note", operator="notlike", value="%b%"),
        ],
    )
    assert build_filter(f) == (
        "(NOT coalesce((attrib->>'note') ILIKE '%a%', FALSE)"
        " AND NOT coalesce((attrib->>'note') ILIKE '%b%', FALSE))"
    )
