"""SQL generated by `create_pagination`.

Running the generated SQL in Postgres is tested in
tests/integration/test_pagination.py
"""

import pytest

from ayon_server.exceptions import BadRequestException
from ayon_server.graphql.resolvers.pagination import (
    SortColumn,
    create_pagination,
    decode_cursor,
    encode_cursor,
)

ATTRIB = "(folders.attrib->>'fps')"


def test_cursor_roundtrip():
    cursor = [None, 5, "a'b", "2024-01-01T00:00:00+00:00"]
    assert decode_cursor(encode_cursor(cursor)) == cursor
    assert decode_cursor(None) == []


def test_invalid_cursor():
    with pytest.raises(BadRequestException):
        decode_cursor("not a cursor")
    with pytest.raises(BadRequestException):
        decode_cursor(encode_cursor({"a": 1}))  # type: ignore[arg-type]


def test_first_page():
    ordering, conditions, cursor = create_pagination(
        ["folders.name", "folders.id"], first=10
    )
    assert conditions == ""
    assert ordering == (
        "ORDER BY folders.name ASC NULLS LAST, folders.id ASC NULLS LAST LIMIT 20"
    )
    assert cursor == "folders.name AS cursor_0, folders.id AS cursor_1"


def test_last_page_is_descending():
    ordering, conditions, _ = create_pagination([ATTRIB, "hierarchy.path"], last=5)
    assert conditions == ""
    assert ordering == (
        f"ORDER BY {ATTRIB} DESC NULLS FIRST, hierarchy.path DESC NULLS FIRST LIMIT 10"
    )


def test_non_nullable_keys_use_row_comparison():
    after = encode_cursor(["foo", "0123"])
    _, conditions, _ = create_pagination(
        ["folders.name", "folders.id"], first=10, after=after
    )
    assert conditions == "(folders.name, folders.id) > ('foo'::text, '0123'::text)"

    before = encode_cursor([42])
    _, conditions, _ = create_pagination(
        ["folders.creation_order"], last=10, before=before
    )
    assert conditions == "folders.creation_order < 42"


def test_after_value():
    after = encode_cursor(["25", "/a"])
    _, conditions, _ = create_pagination(
        [ATTRIB, "hierarchy.path"], first=10, after=after
    )
    key = f"({ATTRIB})::text"
    assert conditions == (
        f"((({key} > '25'::text OR {key} IS NULL))"
        f" OR ({key} = '25'::text AND hierarchy.path > '/a'::text))"
    )


def test_after_null():
    """Only the rows with NULL are after a NULL value"""
    after = encode_cursor([None, "/assets"])
    _, conditions, _ = create_pagination(
        [ATTRIB, "hierarchy.path"], first=10, after=after
    )
    assert conditions == (f"(({ATTRIB}) IS NULL AND hierarchy.path > '/assets'::text)")


def test_before_value():
    before = encode_cursor([5, 3])
    _, conditions, _ = create_pagination(["label", "position"], last=10, before=before)
    assert conditions == (
        "(((label)::numeric < 5::numeric)"
        " OR ((label)::numeric = 5::numeric AND (position)::numeric < 3::numeric))"
    )


def test_before_null():
    """All values are before NULL"""
    before = encode_cursor([None, 5])
    _, conditions, _ = create_pagination(["label", "position"], last=10, before=before)
    assert conditions == (
        "(((label) IS NOT NULL)"
        " OR ((label) IS NULL AND (position)::numeric < 5::numeric))"
    )


def test_after_null_in_last_key():
    after = encode_cursor([None])
    _, conditions, _ = create_pagination(["label"], first=10, after=after)
    assert conditions == "FALSE"

    before = encode_cursor([None])
    _, conditions, _ = create_pagination(["label"], last=10, before=before)
    assert conditions == "((label) IS NOT NULL)"


def test_quotes_are_escaped():
    after = encode_cursor(["it's", "o'k"])
    _, conditions, _ = create_pagination(
        ["label", "folders.name"], first=10, after=after
    )
    assert "'it''s'::text" in conditions
    assert "'o''k'::text" in conditions


def test_invalid_timestamp():
    after = encode_cursor(["yesterday"])
    with pytest.raises(BadRequestException):
        create_pagination(["events.created_at"], first=10, after=after)


#
# Sort direction per column
#

NAME_DESC = SortColumn("folders.name", descending=True)


def test_descending_column_ordering():
    ordering, _, _ = create_pagination([NAME_DESC, "folders.id"], first=10)
    assert ordering == (
        "ORDER BY folders.name DESC NULLS FIRST, folders.id ASC NULLS LAST LIMIT 20"
    )

    # `last` reverses every column
    ordering, _, _ = create_pagination([NAME_DESC, "folders.id"], last=10)
    assert ordering == (
        "ORDER BY folders.name ASC NULLS LAST, folders.id DESC NULLS FIRST LIMIT 20"
    )


def test_all_descending_uses_row_comparison():
    after = encode_cursor(["foo", "0123"])
    _, conditions, _ = create_pagination(
        [NAME_DESC, SortColumn("folders.id", True)], first=10, after=after
    )
    assert conditions == "(folders.name, folders.id) < ('foo'::text, '0123'::text)"


def test_mixed_directions_expand_the_comparison():
    after = encode_cursor(["foo", "0123"])
    _, conditions, _ = create_pagination(
        [NAME_DESC, "folders.id"], first=10, after=after
    )
    assert conditions == (
        "((folders.name < 'foo'::text)"
        " OR (folders.name = 'foo'::text AND folders.id > '0123'::text))"
    )

    before = encode_cursor(["foo", "0123"])
    _, conditions, _ = create_pagination(
        [NAME_DESC, "folders.id"], last=10, before=before
    )
    assert conditions == (
        "((folders.name > 'foo'::text)"
        " OR (folders.name = 'foo'::text AND folders.id < '0123'::text))"
    )


def test_descending_nullable_after_value():
    """In descending order NULLs come first, so they are never after a value"""
    after = encode_cursor(["25", "/a"])
    _, conditions, _ = create_pagination(
        [SortColumn(ATTRIB, True), "hierarchy.path"], first=10, after=after
    )
    key = f"({ATTRIB})::text"
    assert conditions == (
        f"(({key} < '25'::text)"
        f" OR ({key} = '25'::text AND hierarchy.path > '/a'::text))"
    )


def test_descending_nullable_after_null():
    """In descending order all values are after NULL"""
    after = encode_cursor([None, "/a"])
    _, conditions, _ = create_pagination(
        [SortColumn(ATTRIB, True), "hierarchy.path"], first=10, after=after
    )
    assert conditions == (
        f"((({ATTRIB}) IS NOT NULL)"
        f" OR (({ATTRIB}) IS NULL AND hierarchy.path > '/a'::text))"
    )
